apiVersion: apps/v1
kind: Deployment
metadata:
  name: microbe
  labels:
    app: microbe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microbe
  template:
    metadata:
      labels:
        app: microbe
    spec:
      containers:
      - name: microbe
        image: utf18/microbe:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"

---

apiVersion: v1
kind: Service
metadata:
  name: microbe
spec:
  selector:
    app: microbe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microbe
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: microbe.k8s.local
    http:
      paths:
      - path: /
        backend:
          serviceName: microbe
          servicePort: http
