apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: microbe-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microbe
  template:
    metadata:
      labels:
        app: microbe
    spec:
      containers:
      - name: microbe-container
        image: benst/microbe:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: microbe-service
spec:
  ports:
  - name: http
    targetPort: 8080
    port: 80
  selector:
    app: microbe
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microbe-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: microbe.k8s.local
    http:
      paths:
      - path: /
        backend:
          serviceName: microbe-service
          servicePort: http